# Generated by Django 5.0.3 on 2024-07-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0003_rename_user_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('visitor', 'Visitor'), ('admin', 'Admin'), ('other', 'Other')], max_length=64),
        ),
    ]
